In [1]:
import numpy as np

In [2]:
# Compare the time it takes to calculate the mean of a large
# array, using a function I wrote myself that uses a loop that
# iterates through each element of the array vs. the
# np.mean() function, which is optimized for operating
# on large arrays.

# First, define the array and fill it with random numbers
arraysize = 10000
testdata = np.random.randn(arraysize)

# Define my function, which takes an array as input
# and loops through the array to calculate the mean
def my_mean(indata):
    total = 0
    counter = 0
    for ival in indata:
        total += ival
        counter += 1
    
    return (total/counter)

In [3]:
# Use the 'magic command' %timeit to estimate how long
# my function takes to run, on average
%timeit my_mean(testdata)

1.4 ms ± 107 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
# Now, use the %timeit command to estimate how long it
# takes to calculate the mean of the array, when using
# the numpy .mean() method for the array
%timeit testdata.mean()

7.5 µs ± 630 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
# Create a 5x5 array with zeros in the center
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
# Create a 10x10 checkerboard array
arr2 = np.ones((10,10))
arr2[1::2,::2] = 0
arr2[::2,1::2] = 0

In [26]:
arr2

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])