In [1]:
pwd

'/mnt/saturn/jupyterhub_data/erangan1/Psych_027'

In [3]:
import numpy as np

In [36]:
dim1 = 5
dim2 = 5
test = np.zeros((dim1, dim2))

In [37]:
test

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
print(test)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
#np.ones(test[0,:])
test[0,:] = 1
test[4,:] = 1
test[0:4,0] = 1
test[0:4,-1] = 1 #-1 to grab last element

In [40]:
test

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
len(test)

5