In [536]:
import numpy as np
import random as rndm
from statistics import mean

In [309]:
"""PROBLEM 1"""

'PROBLEM 1'

In [354]:
def experiment_setup(nblocks, nconds): #conditions is number of elements in list
    
    int(nblocks)
    int(nconds)
    print(nconds)
    order=[]
    
    for i in range(nblocks):
        p = list(range(1,nconds+1))
        rndm.shuffle(p)
        order.append(p)
        if i > 0:
            while order[i-1][nconds-1] == order[i][0]: 
            #last element in first list vs. #first element in second list
                order.pop(i)
                p = list(range(1,nconds+1))
                rndm.shuffle(p)
                order.append(p)
        
          
    print(order)

In [355]:
experiment_setup(4,3)

3
[[1, 2, 3], [2, 3, 1], [2, 1, 3], [1, 3, 2]]


In [280]:
len(range(1,6+1))

6

In [270]:
range(1,10+1)

range(1, 11)

In [ ]:
"""PROBLEM 2"""

In [537]:
#create an empty array
pairwise_cat = np.array([[range(26)],[range(26)]])
pairwise_cat = np.zeros(shape=(26,26))

In [538]:
text_file = open("midterm_catfr_data.txt", "r") 
catfrdata = text_file.readlines()
test_line = data_line[0].strip().split(",")

In [539]:
test_line

['R1004D', 'catFR1', '0', '1', '1', 'DESK', 'Furniture', '0']

In [540]:
categories = []
recalls_catfr = []
subjects_catfr = []

for iline in catfrdata:
    tmp = iline.strip('\n')
    (subj,task,sess,list_num,serialpos,word,cat,recalled) = tmp.split(',')
    categories.append(cat)
    recalls_catfr.append(int(recalled))
    subjects_catfr.append(subj)

In [541]:
#TURN EVERYTHING INTO AN ARRAY
recalls_catfr = np.array(recalls_catfr, dtype='int')
subjects_catfr = np.array(subjects_catfr)
categories = np.array(categories)

In [542]:
#FIGURE OUT THE UNIQUE STUFF IN THE ARRAYS
subjects_unique = np.unique(subjects_catfr)
categories_unique = np.unique(categories)

subj_mean_recall_by_cat = np.empty((186,26))
subj_mean_recall_by_cat[:]= np.nan

In [543]:
len(subjects_unique)

186

In [544]:
len(categories_unique)

26

In [547]:
subj_mean_recall_by_cat 

array([[0.        , 0.        , 0.08333333, ..., 0.        , 0.        ,
        0.25      ],
       [0.        , 0.58333333, 0.        , ..., 0.33333333, 0.41666667,
        0.41666667],
       [0.        , 0.        , 0.5       , ..., 0.        , 0.125     ,
        0.25      ],
       ...,
       [0.        , 0.        , 0.375     , ..., 0.75      ,        nan,
        0.5       ],
       [0.25      , 0.        , 0.25      , ...,        nan, 0.75      ,
        0.25      ],
       [0.25      , 0.41666667, 0.41666667, ..., 0.5       , 0.83333333,
        0.5       ]])

In [546]:
#CREATES THE 186 BY 26 ARRAY WE TALKED ABOUT IN CLASS
x = -1
y = 0
for isubj in subjects_unique: #runs 186 times
    x+=1
    y=0
    for icat in categories_unique: #runs 26 times
        #goes through list of 72k dataset and sees where the unique subject is found AND the where the unqiue 
        #category is found. output: array of trues and falses whew both of these things are true given the category
        overlap = [np.logical_and(subjects_catfr==isubj,categories==icat)] 
        
        #takes this overlap array and then compares it to the 72k dataset for recalls
        #where, true, it captures that value and takes the mean
        value = np.mean(recalls_catfr[overlap])
        subj_mean_recall_by_cat[x,y] = value
        y+=1
        


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [529]:
subj_mean_recall_by_cat

array([[0.        , 0.        , 0.08333333, ..., 0.        , 0.        ,
        0.25      ],
       [0.        , 0.58333333, 0.        , ..., 0.33333333, 0.41666667,
        0.41666667],
       [0.        , 0.        , 0.5       , ..., 0.        , 0.125     ,
        0.25      ],
       ...,
       [0.        , 0.        , 0.375     , ..., 0.75      ,        nan,
        0.5       ],
       [0.25      , 0.        , 0.25      , ...,        nan, 0.75      ,
        0.25      ],
       [0.25      , 0.41666667, 0.41666667, ..., 0.5       , 0.83333333,
        0.5       ]])

In [530]:
len(subj_mean_recall_by_cat)

186

In [531]:
subj_mean_recall_by_cat[0][:]

array([0.        , 0.        , 0.08333333, 0.        , 0.        ,
       0.08333333, 0.33333333, 0.        ,        nan, 0.        ,
       0.        , 0.        , 0.        , 0.08333333, 0.        ,
       0.        , 0.        , 0.08333333, 0.08333333, 0.        ,
       0.        , 0.08333333, 0.        , 0.        , 0.        ,
       0.25      ])

In [532]:
final = np.empty((26,26))
final[:]= np.nan

In [533]:
subj_mean_recall_by_cat.shape

(186, 26)

In [534]:
type(subj_mean_recall_by_cat)

numpy.ndarray

In [535]:
len(subj_mean_recall_by_cat)

186

In [451]:
len(subj_mean_recall_by_cat[0,:]) #first row length hortizontally 

26

In [452]:
len(subj_mean_recall_by_cat[:,0]) #first column length vertically

186

In [513]:
#LAST PART OF PROBLEM 3
x = 0
y = 0 

for column in range(26): 
    s = subj_mean_recall_by_cat[x,:] #column
    s = s[np.logical_not(np.isnan(s))]
    x+=1
    for row in range(26): 
        #print(row)
        print(y)
        print(x)
        q = subj_mean_recall_by_cat[y,:] 
        q = q[np.logical_not(np.isnan(q))]
        test = np.corrcoef(s,q)
        value_to_append = test[0,1]
        print(value_to_append)
        final[column, row] = value_to_append
        y+=1

0
0
1.0
1
0
-0.19334311660030418
2
0


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [525]:
#TESTING OUR S AND Q WITH ONE ITERATION
s = subj_mean_recall_by_cat[25,:] #column
s = s[np.logical_not(np.isnan(s))]

q = subj_mean_recall_by_cat[24,:] 
q = q[np.logical_not(np.isnan(q))]

test = np.corrcoef(s,q)
value_to_append = test[0,1]
print(value_to_append)

0.20312627697352856


In [ ]:
#THIS IS ALL TEST CODE YOU CAN IGNORE

In [521]:
len(s)

25

In [523]:
len(q)

18

In [524]:
"""x = 0
y = 0
for isubj in subjects_unique:
        overlap = [np.logical_and(recalls_catfr[subjects_catfr==isubj],recalls_catfr[categories==icat])] 
        value = np.mean(overlap)
        subj_mean_recall_by_cat[x,y] = value
"""

#how to do it in one line: np.mean(recalls_catfr[np.logical_and(subjects_catfr==isubj,categories==icat)])

'x = 0\ny = 0\nfor isubj in subjects_unique:\n        overlap = [np.logical_and(recalls_catfr[subjects_catfr==isubj],recalls_catfr[categories==icat])] \n        value = np.mean(overlap)\n        subj_mean_recall_by_cat[x,y] = value\n'

In [233]:
results = np.corrcoef(pairwise_cat,pairwise_cat)


In [230]:
results

array([[1., 1.],
       [1., 1.]])

In [231]:
pairwise_cat

array([0.31890582, 0.35763889, 0.28637006, 0.22020124, 0.29863014,
       0.29264099, 0.3562586 , 0.3135651 , 0.37327348, 0.29210712,
       0.31032078, 0.33577406, 0.34090909, 0.26352288, 0.29419795,
       0.35394385, 0.34065934, 0.30656425, 0.28776738, 0.3574896 ,
       0.34881285, 0.42457507, 0.3287234 , 0.32991803, 0.30104895,
       0.29705882])

In [ ]:
"""for iline in catfrdata:
    rows_to_index = category==cat
    # Put the average recall into the across-subject array
    subjects_array[counter] = np.mean(recalled_array[rows_to_index]"""

In [357]:
"""   for i in range(nconds):
            r=rndm.randint(1,nconds)       
            if len(order) == 0:
                counter = 0
                print(counter)
            if len(order) > 0:
                counter += 1
                while r == order[counter-1]:
                    r=rndm.randint(1,nconds)
            order.append(r)"""

'   for i in range(nconds):\n            r=rndm.randint(1,nconds)       \n            if len(order) == 0:\n                counter = 0\n                print(counter)\n            if len(order) > 0:\n                counter += 1\n                while r == order[counter-1]:\n                    r=rndm.randint(1,nconds)\n            order.append(r)'

In [461]:
"""x = -1
y = 0

for column in subj_mean_recall_by_cat:
    s = subj_mean_recall_by_cat[0,:] #column
    #y+=1
    for row in subj_mean_recall_by_cat[:,0]:
        q = subj_mean_recall_by_cat[:,0] #row
        #x+=1
        test = np.corrcoef(q,s)
        value_to_append = test[0,1]
        print(value_to_append)
        final[0, 0] = value_to_append
        """

ValueError: all the input array dimensions except for the concatenation axis must match exactly